using System;
using System.Collections;
using System.Collections.Generic;
using _Scripts;
using UnityEngine;
using UnityEngine.UI;

public class TopMenu : MonoBehaviour
{
    [SerializeField] private Image[] _覺mages;
    [SerializeField] private Color _dis;
    
    
    private int iteration = 1;

    private void Start()
    {
        IterationController.OnIterationCompleted += On;
        IterationController.OnIterationCompletedWithKingLoss += On;
    }

    private void OnDestroy()
    {
        IterationController.OnIterationCompleted += On;
        IterationController.OnIterationCompletedWithKingLoss += On;
    }

    private void On()
    {
        iteration++;
        Adjust();
    }

    private void Adjust()
    {
        for (int i = 0; i < iteration; i++)
        {
            _覺mages[i].gameObject.SetActive(true);
        }
        
        for (int i = 0; i < iteration-1; i++)
        {
            _覺mages[i].color = _dis;
        }
        
        _覺mages[iteration].color = Color.white;
    }
}
